[![Google Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/PyGIS222/Fall2019/blob/master/LessonM34_Dictionaries.ipynb)

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/PyGIS222/Fall2019/master?filepath=LessonM34_Dictionaries.ipynb)

### Notebook Lesson 3.4

# Object Type: Dictionaries

This Jupyter Notebook is part of Module 3 of the course GIS222 (Fall2019).

This lesson discusses the Python object type **Dictionaries**. Carefully study the content of this Notebook and use the chance to reflect the material through the interactive examples.

### Sources
This lesson is an adaption of the lesson [Understanding Dictionaries in Python 3](https://www.digitalocean.com/community/tutorials/understanding-dictionaries-in-python-3) of the [Digital Ocean Community](https://www.digitalocean.com/community).

---

## Part A: Introduction

Table 1 provides a comprehensive overview of Python object classifications. The table gives information about their mutability and their category. The sequential character of strings and lists was emphasized in the last notebooks. Now we want to look at another type of objects in Python that provides the most flexibility: *Dictionaries*. Tuples, Sets and Files will be discussed in the upcoming notebooks.

Table 1. *Object Cassifications* (Lutz, 2013)

| Object Type       | Category  |  Mutable? |    
| :---------:       | :-------: | :-------: |
| Numbers (all)     | Numeric   | No        |   
| Strings           | Sequence  | No        |   
| Lists             | Sequence  | Yes       |   
| Dictionaries      | Mapping   | Yes       |   
| Files             | Extention | N/A       |   
| Tuples            | Sequence  | No        |   
| Sets              | Set       | Yes       |   
| `frozenset`       | Set       | No        |   

The dictionary is Python’s built-in *mapping* type. Dictionaries map *keys* to *values* and these key-value pairs provide a useful way to store data in Python. Since dictionaries are mutable, they allow **mutable data mapping**. 

<div class="alert alert-info">

**Note**
Dictionaries are an unordered collection of arbritrary objects (no sequences) of variable length. They are similar to lists, but provide more general data access, since accessing the content is not limited to index numbers and it can be achieved by other types of indices. 
</div>

Dictionaries are typically used to hold data that are related, such as the information contained in an ID or a user profile. They are constructed with curly braces on either side `{` `}`.

A simple example for a dictionary looks like this:

In [1]:
sammy = {'username': 'sammy-shark', 'online': True, 'followers': 987}
type(sammy)

dict

In addition to the curly braces, there are also colons (`:`) throughout the dictionary.

The words to the left of the colons are the keys. *Keys* can be made up of any immutable data type. The keys in the dictionary above are: 

*    `'username'`
*    `'online'`
*    `'followers'`

Keys have to be of immutable object type, like numbers or strings. Each of the keys in the above example are string values.

The words to the right of the colons are the values. Values can be comprised of any data type. The values in the dictionary above are:

*    `'sammy-shark'`
*    `True`
*    `987`

Each of these values is either a string, Boolean, or integer. 

Let’s print out the dictionary `sammy`:

In [39]:
print(sammy)

{'username': 'sammy-shark', 'online': False, 'followers': 987}


Looking at the output, the order of the key-value pairs may have shifted. In Python version 3.5 and earlier, the dictionary data type is unordered. However, in Python version 3.6 and later, the dictionary data type remains ordered. Regardless of whether the dictionary is ordered or not, the key-value pairs will remain intact, enabling us to access data based on their relational meaning. 

# Part B: Accessing Dictionary Elements

We can call the values of a dictionary by referencing the related keys.

### Accessing Data Items with Keys

Because dictionaries offer key-value pairs for storing data, they can be important elements in your Python program.

If we want to isolate Sammy’s username, we can do so by calling `sammy['username']`. Let’s print that out:


In [3]:
print(sammy['username'])

sammy-shark


Dictionaries behave like a database in that instead of calling an integer to get a particular index value as you would with a list, you assign a value to a key and can call that key to get its related value. 

By invoking the key `'username'` we receive the value of that key, which is `'sammy-shark'`.

The remaining values in the `sammy` dictionary can similarly be called using the same format:



In [4]:
sammy['followers']

987

In [5]:
sammy['online']

True

By making use of dictionaries’ key-value pairs, we can reference keys to retrieve values.

### Using Methods to Access Elements

In addition to using keys to access values, we can also work with some built-in methods is a placeholder for the name of a dictionary):

*    `.keys()` isolates keys
*    `.values()` isolates values
*    `.items()` returns items in a list format of `(key, value)` tuple pairs

To return the keys, we would use the `.keys()` method. In our example, that would use the variable name and be `sammy.keys()`. Let’s pass that to a `print()` method and look at the output:

In [6]:
print(sammy.keys())

dict_keys(['username', 'online', 'followers'])


In [7]:
type(sammy.keys())

dict_keys

We receive output that places the keys within an iterable view object of the `dict_keys` class. The keys are then printed within a list format.

This method can be used to query across dictionaries. For example, we could take a look at the common keys shared between two dictionary data structures:

In [1]:
sammy = {'username': 'sammy-shark', 'online': True, 'followers': 987}
jesse = {'username': 'JOctopus', 'online': False, 'points': 723}

The dictionary `sammy` and the dictionary `jesse` are each a user profile dictionary. 

Their profiles have different keys, however, because Sammy has a social profile with associated followers, and Jesse has a gaming profile with associated points. The two keys they have in common are `username` and `online` status, which we can find when we run this small program:

In [9]:
for common_key in sammy.keys() & jesse.keys():
    print(sammy[common_key], jesse[common_key])

sammy-shark JOctopus
True False


We could certainly improve on the program to make the output more user-readable, but this illustrates that the method `.keys()` can be used to check across various dictionaries to see what they share in common or not. This is especially useful for large dictionaries.

Similarly, we can use the `.values()` method to query the values in the `sammy` dictionary, which would be constructed as `sammy.values()`. Let’s print those out:

In [10]:
sammy = {'username': 'sammy-shark', 'online': True, 'followers': 987}
print(sammy.values())

dict_values(['sammy-shark', True, 987])


Both the methods `keys()` and `values()` return unsorted lists of the keys and values present in the `sammy` dictionary with the view objects of `dict_keys` and `dict_values` respectively.

If we are interested in all of the items in a dictionary, we can access them with the `items()` method:

In [11]:
print(sammy.items())

dict_items([('username', 'sammy-shark'), ('online', True), ('followers', 987)])


The returned format of this is a list made up of `(key, value)` tuple pairs with the `dict_items` view object. We will discuss tuples in the next notebook lesson.

We can iterate over the returned list format with a `for` loop. For example, we can print out both at the same time keys and values of a given dictionary, and then make it more human-readable by adding a string:

In [12]:
for key, value in sammy.items():
    print(key, 'is the key for the value', value)

username is the key for the value sammy-shark
online is the key for the value True
followers is the key for the value 987


The `for` loop above iterated over the items within the sammy dictionary and printed out the keys and values line by line, with information to make it easier to understand by humans.

We can use built-in methods to access items, values, and keys from dictionary data structures.

# Part C: Modifying Dictionaries

Dictionaries are a mutable data structure, so you are able to modify them. In this section, we’ll go over adding and deleting dictionary elements.

### Adding and Changing Dictionary Elements

Without using a method or function, you can add key-value pairs to dictionaries by using the following syntax:

`dict[key] = value`.

We’ll look at how this works in practice by adding a key-value pair to a dictionary called `usernames`:

In [13]:
usernames = {'Sammy': 'sammy-shark', 'Jamie': 'mantisshrimp54'}

In [14]:
usernames['Drew'] = 'squidly'

In [15]:
print(usernames)

{'Sammy': 'sammy-shark', 'Jamie': 'mantisshrimp54', 'Drew': 'squidly'}


We see now that the dictionary has been updated with the `'Drew': 'squidly'` key-value pair. Because dictionaries may be unordered, this pair may occur anywhere in the dictionary output. If we use the `usernames` dictionary later in our program file, it will include the additional key-value pair.

Additionally, this syntax can be used for modifying the value assigned to a key. In this case, we’ll reference an existing key and pass a different value to it.

Let’s consider a dictionary `drew` that is one of the users on a given network. We’ll say that this user got a bump in followers today, so we need to update the integer value passed to the `'followers'` key. We’ll use the `print()` function to check that the dictionary was modified.

In [16]:
drew = {'username': 'squidly', 'online': True, 'followers': 305}

In [17]:
drew['followers'] = 342

In [18]:
print(drew)

{'username': 'squidly', 'online': True, 'followers': 342}


In the output, we see that the number of followers jumped from the integer value of 305 to 342.

We can also add and modify dictionaries by using the `.update()` method. This varies from the `append()` method available in lists.

In the `jesse` dictionary below, let’s add the key `'followers'` and give it an integer value with `jesse.update()`. Following that, let’s `print()` the updated dictionary.

In [20]:
jesse = {'username': 'JOctopus', 'online': False, 'points': 723}

In [21]:
jesse.update({'followers': 481})

In [22]:
print(jesse)

{'username': 'JOctopus', 'online': False, 'points': 723, 'followers': 481}


From the output, we can see that we successfully added the `'followers': 481` key-value pair to the dictionary `jesse`.

We can also use the `.update()` method to modify an existing key-value pair by replacing a given value for a specific key.

Let’s change the online status of Sammy from `True` to `False` in the sammy dictionary:

In [23]:
sammy = {'username': 'sammy-shark', 'online': True, 'followers': 987}

In [24]:
sammy.update({'online': False})

In [25]:
print(sammy)

{'username': 'sammy-shark', 'online': False, 'followers': 987}


The line `sammy.update({'online': False})` references the existing key `'online'` and modifies its Boolean value from `True` to `False`. When we call to `print()` the dictionary, we see the update take place in the output.

To add items to dictionaries or modify values, we can use wither the `dict[key] = value` syntax or the method `.update()`.

### Deleting Dictionary Elements

Just as you can add key-value pairs and change values within the dictionary data type, you can also delete items within a dictionary.

To remove a key-value pair from a dictionary, we’ll use the following syntax:

`del dict[key]`

Let’s take the `jesse` dictionary that represents one of the users. We’ll say that Jesse is no longer using the online platform for playing games, so we’ll remove the item associated with the `'points'` key. Then, we’ll print the dictionary out to confirm that the item was deleted:

In [58]:
jesse = {'username': 'JOctopus', 'online': False, 'points': 723, 'followers': 481}

In [59]:
del jesse['points']

In [60]:
print(jesse)

{'username': 'JOctopus', 'online': False, 'followers': 481}


The line `del jesse['points']` removes the key-value pair `'points': 723` from the jesse dictionary.

If we would like to clear a dictionary of all of its values, we can do so with the `.clear()` method. This will keep a given dictionary in case we need to use it later in the program, but it will no longer contain any items.

Let’s remove all the items within the `jesse` dictionary:

In [1]:
jesse = {'username': 'JOctopus', 'online': False, 'points': 723, 'followers': 481}

In [2]:
jesse.clear()

In [33]:
print(jesse)

{}


The output shows that we now have an empty dictionary devoid of key-value pairs.

If we no longer need a specific dictionary, we can use `del` to get rid of it entirely:

In [35]:
del jesse

When we run a call to `print()` after deleting the jesse dictionary, we’ll receive the `NameError`:

In [38]:
print(jesse)

NameError: name 'jesse' is not defined

Because dictionaries are mutable data types, they can be added to, modified, and have items removed and cleared.

### Nested Dictionaries and Lists

A for-loop on a dictionary in the syntax of *list comprehensions* iterates over its keys by default. This returns the keys saved in a list object (in contrast to the `keys()` method). The keys will appear in an arbitrary order.



In [91]:
[ key for key in jesse ]

['username', 'online', 'points', 'followers']

In addition to that, lists and dictionaries can be combined, i.e. nested in order to design various useful data structures. For example, instead of saving the user information of `sammy`, `jesse` and `drew` in three different dictionaries, ...

In [61]:
sammy = {'username': 'sammy-shark', 'online': True,  'points': 120, 'followers': 987}
jesse = {'username': 'JOctopus'   , 'online': False, 'points': 723, 'followers': 481}
drew  = {'username': 'squidly'    , 'online': False, 'points': 652, 'followers': 532}

... we coul simply feed the data into a nested dictionary - a dictionary of dictionaries:

In [ ]:
AppUsers_dictDict = {
    'sammy': {'username': 'sammy-shark', 'online': True,  'points': 120, 'followers': 987},
    'jesse': {'username': 'JOctopus'   , 'online': False, 'points': 723, 'followers': 481},
    'drew' : {'username': 'squidly'    , 'online': False, 'points': 652, 'followers': 532}
}

... or we coul generate a dictionary nesting information in lists:

In [92]:
AppUsers_dictList = {
    'names'    : ['sammy', 'jesse', 'drew' ] ,
    'usernames': ['sammy-shark', 'JOctopus', 'squidly' ] ,
    'online'   : [True,  False, False] ,
    'points'   : [120,   723,   652  ] ,
    'followers': [987,   481,   532  ]
}

... alternatively, dictionaries in a list:

In [93]:
AppUsers_listDict = [
    {'name': 'sammy', 'username': 'sammy-shark', 'online': True,  'points': 120, 'followers': 987},
    {'name': 'jesse', 'username': 'JOctopus'   , 'online': False, 'points': 723, 'followers': 481},
    {'name': 'drew' , 'username': 'squidly'    , 'online': False, 'points': 652, 'followers': 532}
]

To access the individual elements of such nested objects, the syntax has to follow the hierarchy of the nested elements. For example, referencing a nested list-dictionary combination is has to be achieved through a combination of dictionary keys and list indexes. 

Let's retrieve the username of jesse from the three nested objects. Elements in nested dictionaries can be referenced through keys of the various nesting levels:

`dictname[‘keyLevel1’][‘keyLevel2’][...]`

For the example `AppUsers_dictDict`, the respective literal is:

In [106]:
AppUsers_dictDict['jesse']['username']

'JOctopus'

If lists and dictionaries were combined, keys and indexes have to be combined respectively:

`dictname[‘key’][indexnumber]` or `dictname[indexnumber][‘key’]`

For the examples `AppUsers_dictList` and `AppUsers_listDict` above:

In [107]:
AppUsers_dictList['usernames'][1]

'JOctopus'

In [108]:
AppUsers_listDict[1]['username']

'JOctopus'

# Summary

Dictionaries are made up of key-value pairs and provide a way to store data without relying on indexing. This allows us to retrieve values based on their meaning and relation to other data types. 

* Elements in dictionaries are directly accessible by keys.
* Keys have to be of immutable object type, like numbers or strings.
* Lists are mutable, they can't be used as keys, but they can be used as nested values.
* A list comprehension performed on a dictionary iterates over its keys by default. The keys will appear in an arbitrary order.

Most common specific operations (methods) are: `pop`, `keys`, `values`, `items`, `get`. A comprehensive overview of built-in dictionary operations, functions and methods is provided here: https://www.tutorialspoint.com/python/python_dictionary.htm
